### ISSUE TITLE
Should the transitions example be reworked / removed / clarified?

### ISSUE THREAD

**Issue by birtles** [mozdevs/Animation-examples#18]
For the source code comparison, the transitions example is correct, but in the near future, when browsers support additive animation we will be able to make this a lot simpler by just writing:

``` js
  el.animate({ transform: 'scale(1.25)' }, 300);
```

Ultimately, however, CSS transitions are a better fit for this use case since they do the automatic shortening of the reverse transition (which I think you worked around in this case by using a shorter duration for the Web Animations example so you don't notice).

Although this example shows the correspondence well, perhaps it deserves a note to say, "this shorter syntax is coming soon" or "this doesn't do shortening" ?

**Comment by belen-albeza** [comment]
Yes, we are aware of this. But since I wanted to show how to mimick a CSS animation on `hover` I wanted to include the example. I will add a note that once implicit `from` values are supported, the code should change. However, I don't think that "shorter syntax" is the right wording, since they do different things.

I agree that the best way to handle these animations is via CSS, but then we wouldn't be able to modify them on the fly depending on user settings :(

**Comment by belen-albeza** [comment]
Fixed 
![screen shot 2016-08-01 at 11 34 14](https://cloud.githubusercontent.com/assets/63681/17289904/f8e4cfbe-57db-11e6-9eac-d6acefa3d3bd.png)

**Comment by birtles** [comment]
Thanks. Also:
- You won't actually need the array notation, i.e. instead of `transform: ['scale(1.25)']` you will be able to write just `transform: 'scale(1.25)'`
- You will soon actually be able to modify CSS transitions on the fly doing something like:

``` js
var transition = elem.getAnimations({ transitionProperty: 'width' })[0];
transition.effect = new KeyframeEffect(transition.effect);
effect.setKeyframes({ /* new keyframes */ });
```

I don't expect you to mention that final point and I agree it still makes sense to show the rough equivalent to a transition, but I thought you might be interested to know.

**Comment by belen-albeza** [comment]
> You will soon actually be able to modify CSS transitions on the fly doing something like:
> 
> ``` js
> var transition = elem.getAnimations({ transitionProperty: 'width' })[0];
> transition.effect = new KeyframeEffect(transition.effect);
> effect.setKeyframes({ /* new keyframes */ });
> ```

Well… kind of. Since `getAnimations` only return the animations that are currently running, you need to know beforehand when those animations will be triggered, and which properties they would be animating… So, as a developer, if I need to have such strong coupling between CSS and JS, I might just do the whole thing in JS.

**Comment by birtles** [comment]
Yes, that's right! The use case is for extending CSS transitions. You can see [an example here](https://bugzilla.mozilla.org/show_bug.cgi?id=1049975#c44) (see part-way through that comment where it talks about replacing a red&rarr;green transition with one that goes red&rarr;yellow&rarr;green). The advantage of doing that is you can continue to use existing means of triggering/cancelling transitions and it has graceful fallback if the browser doesn't support the Web Animations API.
